---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install Apache2 Packages 
    apt:  name=apache2 state=present

  - name: Start Apache Service
    service: name=apache2 state=started enabled=true

  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8 
    apt: name=default-jdk state=present


  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"

  - name: Copy Index Page Files
    copy: src=templates/apps dest=/var/www/html mode=0644

  - name: Remove ROOT folder initially
    command: rm -rf /opt/SP/apps/tomcat/webapps/ROOT

  - name: Copy Kalinga music store Project War Files
    copy: src=templates/kalingamusic-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ROOT.war mode=0644
    notify: 
    - Restart Tomcat

  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
